### ISSUE TITLE
.tap_package file has been deprecated

### ISSUE THREAD

**Issue by mjuric** [lsst/astropy#2]
.. in favor of setting TAP_PACKAGE=1 in the eupspkg.cfg.sh file (grep c.l.o for more details, I think)

**Comment by timj** [comment]
I know. I do both. I thought the policy was for us to do both during transition whilst there are still people around who are not using EUPS v2.x.

**Comment by jdswinbank** [comment]
I believe Jenkins currently uses a version of EUPS which doesn't support `TAP_PACKAGE=1`.  The [Developer Guide](http://developer.lsst.io/en/latest/build-ci/third_party.html#build-third-party-other-files) suggests doing both.

**Comment by mjuric** [comment]
Right, doing both is the thing to do but the current eupspkg.cfg.sh on master doesn't have TAP_PACKAGE set. Unless github mobile is messing with me...

**Comment by timj** [comment]
Sigh. You are right. I had it in and then copied the file from numpy and over wrote it. Will fix. Sorry.
